apiVersion: v1
kind: Pod
metadata:
  name: copy-file-pod
  namespace: argowf
spec:
  containers:
  - name: copy-file
    image: ubuntu:latest
    command:
      - "sleep"
      - "604800"
    volumeMounts:
    - name: data
      mountPath: /opt/ml/processing
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: churn-data-pvc
  - name: temp
    emptyDir: {}