apiVersion: v1
kind: PersistentVolume
metadata:
  name: churn-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/churn-data  # On-prem storage path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: churn-data-pvc
  namespace: argowf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
