apiVersion: v1
kind: PersistentVolume
metadata:
  name: churn-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany  # Can use RWX with NFS
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-shared
  nfs:
    server: 192.168.1.100
    path: /srv/nfs/kubernetes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: churn-data-pvc
  namespace: argowf
spec:
  accessModes:
    - ReadWriteMany  # Allows multiple pods/nodes
  resources:
    requests:
      storage: 10Gi
  volumeName: churn-data-pv