apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argowf # The namespace where your Argo workflows and SeldonDeployments will run
  name: seldon-deployment-manager
rules:
- apiGroups: ["machinelearning.seldon.io"]
  resources: ["seldondeployments", "seldondeployments/finalizers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-can-manage-seldon-deployments
  namespace: argowf
subjects:
- kind: ServiceAccount
  name: argo-workflow # The service account used by your Argo workflows
  namespace: argowf
roleRef:
  kind: Role
  name: seldon-deployment-manager
  apiGroup: rbac.authorization.k8s.io